# Datasource
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=auth
quarkus.datasource.password=auth123
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/authdb

# Hibernate
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true

# JWT
mp.jwt.verify.issuer=https://authservice.com
quarkus.smallrye-jwt.enabled=true
smallrye.jwt.sign.key.location=privateKey.pem
mp.jwt.verify.publickey.location=publicKey.pem
smallrye.jwt.new-token.lifespan=28800